name: Docker Image CI

on:
  push:
    tags: '*'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hellojukay/httpfs:$(date +%s)
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        stable: 'true'
        go-version: '^1.13.1'
    - name: build
      run: go get github.com/mitchellh/gox  && mkdir dist && perl build.pl && ls -al
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/*
        asset_name: mything
        tag: ${{ github.ref }}
        overwrite: true
